### ISSUE TITLE
Load balancer + auto-scaling for production setup

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#10]
Configure the Elastic Load Balancing and Auto Scaling for the IIIF AMI for the use in production deployment.

Improve documentation started in ALPHA milestone - under #5 - and run additional performance tests.

**Comment by o1da** [comment]
Done. Elastic Load Balancing with Auto Scaling is configured and tested.
Documentation is extended with "Production deployment" part, where current configuration is described and useful tips are provided.
