### ISSUE TITLE
S3FS nofile patch

### ISSUE THREAD

**Issue by o1da** [klokantech/hawk#11]
Another patch for S3FS is needed. We have to suppress S3FS feature when if there is a request to file which is not on S3, it tries to check if the provided filename isn't name of folder or path instead, so another requests to S3 are invoked.

Look at https://github.com/s3fs-fuse/s3fs-fuse/blob/master/src/s3fs.cpp to change S3FS behaviour in this way.

**Comment by klokan** [comment]
@MartinMikita coding to be done in a 'nofile' branch under https://github.com/klokantech/s3fs-fuse

**Comment by MartinMikita** [comment]
It is impossible to avoid checking for folder, because reading file "jp2/test.jp2" first is checking whether parent object is accessible - it is checking for "jp2".

Only avoiding checking for "path_$folder$" and listing bucket can be removed.

**Comment by MartinMikita** [comment]
https://github.com/klokantech/s3fs-fuse/commit/46247d581fc42f4a2bd57089b582364b9887c98a

**Comment by klokan** [comment]
Thanks @MartinMikita.

Please remove the branch, create it again and push a clean commit which is not changing the end-of-lines.

The target of this ticker is to make (if possible) only one S3 HTTP query to get information whether a file (key) exists or not, when a process makes query similar to "ls -lah path/subpath/filename.jp2" on a mounted s3fs disk.

How many requests to S3 are made now to get information that file like "path/subpath/filename.jp2" does not exist?

**Comment by MartinMikita** [comment]
Request to the file is called by FUSE with the function `s3fs_getattr` on each part of the path.

Firstly FUSE is getting information about `/path`, and s3-fuse is checking 4 HTTP queries:
- `/path` (as file)
- `/path/` (as directory), S3 on the request above returns 404
- `/path_$folder$`
- list bucket operation on `/path`

Now I am getting for the not-existent file 2 same callings `s3fs_getattr`

**Comment by klokan** [comment]
The last 2 steps from the 4 should be removed - which I believe you did already above.
I expect that 'as directory' check is in fact a request to S3 for existence of a key with given prefix, right?
Please remove the existing branch and push it again with a clean commit without malformed end-of-lines.

**Comment by MartinMikita** [comment]
I made more research:

FUSE is starting from the first part of path. On each part it is calling `s3fs_getattr`.
But this method is checking parents part of the path also.

Demonstration:
Search path: `/a/b/c/file.tif
The beginning is the same for existent/non-existent file:
1. part `/a` : 2 requests (`/a` and `/a/`, the last succeed)
2. part `/a/b` : 4 requests, 2 per each part (firstly parent `/a` then `/a/b`)
3. part `/a/b/c` : 6 requests, for `/a/b`, `/a` and last `/a/b/c`
   Now we have 12 requests (without cache) to S3 for just folder.

Existent file has 7 more requests: 6 for parent objects (directories): `/a/b/c`, `/a/b`, `/a` and 1 request for the file.

Non-existent file has 6 request for parent objects + 4 for non-existent (3 simple request, 1 list of buckets) file.
And this 10 requests are made twice (I do not know why).

In the final, existent file 19 requests, not-existent file 32 requests (without any cache).

I am thinking, that maybe we can avoid checking for parents objects, while they are checked from FUSE before file. With cache it does not have sense, altough

**Comment by MartinMikita** [comment]
Change rewritten in https://github.com/klokantech/s3fs-fuse/commit/6c75dffd3126a51e1159ba16bebfcce396759014

I tried remove checking parents for object, and in result (with change above):
Existent file: 7 requests
Not existent file: 8 requests

**Comment by klokan** [comment]
@o1da part of the deploy should be compiling of the hawk branch of s3fs-fuse:
https://github.com/klokantech/s3fs-fuse/tree/hawk

Finished. In case of issues we reopen.

**Comment by MartinMikita** [comment]
Branch hawk of s3fs-fuse is not working as expected

**Comment by MartinMikita** [comment]
s3fs-fuse is working as expected, problem was with python boto library.

Important Note!

Amazon S3 has no "folder structure" - it is just list of keys created by user.
"Folder" is created as special key "path/", which is empty. (see [comment](http://stackoverflow.com/questions/1939743/amazon-s3-boto-how-to-create-folder/25033276#25033276))

@o1da was uploading sequences as "folder/file.jp2", and boto library does not create "folder" key automatically - it is need to be created manually as "folder/"

Requests to Amazon S3 for "folder/" was returned as "key does not exists" for such cases.
Cyberduck or other software are visually displaying files in the bucket as tree with folders, but we don't find any way how to check whether "folder/" key exists or not.

Action "Create folder" in Cyberduck was creating empty key - that was I testing and it was working well.

@o1da fixed issue in python scripts
