### ISSUE TITLE
S3FS local file cache cleaning

### ISSUE THREAD

**Issue by o1da** [klokantech/hawk#12]
S3FS uses local file cache to speed up requests to often needed files. Local file cache is a common folder and S3FS doesn't clean it by itself. So it can possibly grows out of boundary of the local filesystem. 

Some script which will look at last access time to these files and delete long time unused ones is needed. It can be probably run periodically by cron.

**Comment by klokan** [comment]
Inspiration:
https://github.com/s3fs-fuse/s3fs-fuse/blob/master/test/sample_delcache.sh

**Comment by MartinMikita** [comment]
S3FS has local stat cache and file cache.
It is possible to set timeout for stat cache (information about existing key - file size).

I find now this comment with code for opening (reading) file from s3fs:

```
  // clear stat for reading fresh stat.
  // (if object stat is changed, we refresh it. then s3fs gets always
  // stat when s3fs open the object).
  StatCache::getStatCacheData()->DelStat(path);
```

If we keep stat cache for file, which will be deleted, than `ls` command will succeed until timeout, displaying file info (size) for already not-existing file.
But, when file is opened (to read, which IIIFserver does), than stat cache is deleted and new info from S3 are requested.
If local file cache size differ from S3, new file is downloaded.

Missing (cleaned) stat cache and reading such file will not break it - new stat cache downloaded and file read (if exist)

**Comment by o1da** [comment]
Script for periodical s3fs local cache cleaning is prepared and deployed on the iiif.embedr.eu server. It isn't run by cron internally but by supervisor. Installation protocol was updated.
