### ISSUE TITLE
Ingest task for a single file [C.2]

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#13]
Create function for ingest task of a single file in Python. It receives as arguments the values specified in the Ingestion API - for one file from the . See: https://github.com/klokantech/hawk/wiki/C.Ingest

For example:

``` json
    "id": "ID-1",
    "url": "http://provider.eu/link/to/highres/image.jpg",
    "rights": "CC-BY",
    "provider": "Name of institution",
    "provider_link": "http://provider.eu/link-to-image"
```

It downloads the highres image from `url`, encodes it with `kdu_compress` and uploads it to Amazon S3 with `boto` library. It returns status code - whether it was successful or not.

The provided metadata must be stored in our central database.

The ingest function must be able to run independent (possibly on a different machine) from the Flask.

**Comment by mzeinstra** [comment]
Do you require us to compile the fields that should be minimally stored here? Also this has impact on the embedding features of the service, they will require a attribution line below the viewer. Right?

**Comment by klokan** [comment]
Yes. The list of preferred fields would be nice - as it was not specified yet.

I expected to be very simple - following the IIIF Presentation API requirements:
http://iiif.io/api/presentation/2.0/#presentation-resource-properties

or alternatively to be based on the DublinCore 15 base elements:
See: http://en.wikipedia.org/wiki/Dublin_Core#Dublin_Core_Metadata_Element_Set_Version_1.1

The idea is to keep it as simple as possible and use the existing standards.
Suggestions and comments are welcome.

**Comment by mzeinstra** [comment]
Hi,

I've written a quick data model for the ingestion API as I see it, I've also mapped these to the services that are planned. 

Does this match your thoughts on this?

You can find the 'model' here: https://docs.google.com/document/d/1fNnDGo5cFOPgfDV61BQTvCbW6iJbFit0GQfwphgf7B4/edit#

**Comment by klokan** [comment]
An early implementation done and deployed.
We need to refactor and clean the code now, create a set of tests, protect the endpoint with password, etc.

Usage test a la:
`$ curl -H "Content-Type: application/json" -X POST -d @ingest.json http://embedhawk.klokantech.com/ingest`

with ingest.json similar to:

``` json
[
{
  "id": "myidentifier1",
  "url": ["http://apod.nasa.gov/apod/image/0704/m45_spitzerR.jpg"],
  "title": "NASA image ingested by Klokan",
  "rights": "CC-BY",
  "provider": "NASA",
  "provider_link": "http://www.nasa.gov/"
}
]
```

This returns id of a batch. It is possible to ask for the status of the batch by:
http://embedhawk.klokantech.com/ingest?batch_id=id

and if it is "ok" access the file in embed and iiif endpoints:
http://embedhawk.klokantech.com/myidentifier1

**Comment by o1da** [comment]
Ingest with sequences and randomly delayed processing of image (if the first attempt fails) is prepared.
- [x] Secure access needs to be added (via nginx).
- [x] Delete task to be done via celery (removing S3 files)
- [x] Update task may delete S3 files as well (if previously downloaded files are missing in new ingest)
- [x] Deleting of an item with ERROR status because of incomplete sequence should be possible - it deletes the downloaded sequences from Amazon S3
- [x] Report all issues on valid JSON structure as an error message in JSON response (related to #26 and #25)

**Comment by klokan** [comment]
The tasks here still missing:
- [x] Password for Ingest API to be added in the Installation Protocol.
- [x] If Item fails on Ingest because any of the urls in sequence fails - we will delete all downloaded items to keep the S3 storage clean
- [x] Ensure updates of sequences 1,2,3 and 4,2,3 runs as described in #37, but no reschuffling

**Comment by o1da** [comment]
Done. If someone changes order of url in the ingest for the specific item, the S3 storage is updated correctly (it can be optimized #37). But we should discuss connection of ingest with cache cleaning in #12 (s3fs local file cache and memcached too), to ensure that only fresh data remains on the complete service chain after the ingest.
