### ISSUE TITLE
Embedding App [B.1]

### ISSUE THREAD

**Issue by o1da** [klokantech/hawk#14]
Let's create embedding application in the pythonic flask environment. Development process can be done against sqlite database, but it can be easily replaced with another database system, because flask uses object mapping module - SQLAlchemy.

Embedding application provides public per-object embedding endpoints showing the image and basic metadata. All of these end points must be prepared:
- oEmbed provider (at `/oembed/[UNIQUE-ID]`) (static image) #8 
- iFrame embedding (at `/[UNIQUE-ID]`) (zoomable viewer or static image) #7  
- IIIF protocol Presentation API (at `/iiif/[UNIQUE-ID]/manifest.json`) (IIIF service) #15

The same file application will integrate the Ingestion API endpoint:
- `/ingest` to add/delete objects.

First version defines the data model and calls the ingest function (developed under #13) directly.
Later on the ingestion will trigger an ingest task which will run independent (possibly on a different machine) from the Flask.

To be set with auto-deploy on the test EC2 machine #21 
Ideally we should start also with unit-testing #25

**Comment by klokan** [comment]
After internal discussion - let's put the app to the Docker Compose and use Redis as the main key-value store, which will be used as storage for the queue as well.

**Comment by o1da** [comment]
Redis and Docker Compose are used know. App can be tested on http://embedhawk.klokantech.com/.
I have there one testing item with id "000-test2" so manifest is there:
http://embedhawk.klokantech.com/iiif/000-test2/manifest.json
And iFrame is there:
http://embedhawk.klokantech.com/000-test2

**Comment by klokan** [comment]
I wonder if not to make the the URLs look more Restful - in a sense `/[object-id]/format`.
Is there a technical issue preventing this, such as collision of the URLs?
It may look better. Let's discuss it on the next internal meeting.

Update: Simplified URLs in ticket #29

**Comment by klokan** [comment]
The core of embedding app is now finished.
Remaining tasks and improvements are in other tickets.
