### ISSUE TITLE
IIIF protocol Presentation API template [B.4]

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#15]
Define template for minimal validad manifest.json for a single file hold in the database.

It is to provide:
- IIIF protocol Presentation API (at http://embed.europeana.eu/iiif/[UNIQUE-ID]/manifest.json) (IIIF service)

The manifest test must pass the validation step: http://iiif.io/api/presentation/validator/

Specification: http://iiif.io/api/presentation/2.0/

We should also try to load the image in Mirador 2.0: http://projectmirador.org/

**Comment by klokan** [comment]
We could use the Factory to produce the IIIF manifests serialised into JSON:
https://github.com/IIIF/presentation-api/tree/master/implementations/manifest-factory

**Comment by o1da** [comment]
Basic manifest is prepared and validated - can be checked on http://iiif.io/api/presentation/validator/service/validate?url=http%3A%2F%2Fembedhawk.klokantech.com%2Fiiif%2F000-test2%2Fmanifest.json&version=2.0&format=html
It produces some warnings but about optional parameters. Examples from http://iiif.io/api/presentation/2.0/example/fixtures/ don't use them too.

How should I test it with Mirador 2.0? There is a live demo - I can set there url, but nothing happens if I fill url of the manifest of my testing item. Should I install the Mirador somewhere locally?

**Comment by klokan** [comment]
Great for the validation! Let's review the importance of the warnings during the validation on next internal meeting. These are probably not essential...

Test of the Mirador to be done at: http://projectmirador.org/, Live Demo - Change Layout 3x1 - "+" Add Item and our manifest URL.
https://groups.google.com/d/topic/iiif-discuss/P38AgtE0P4U/discussion

For a sample manifest it runs fine:
http://www.e-codices.unifr.ch/metadata/iiif/kba-0003/manifest.json

Hawk manifest is missing CORS headers. JavaScript console tells:

```
XMLHttpRequest cannot load http://embedhawk.klokantech.com/iiif/000test2/manifest.json.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://projectmirador.org' is therefore not allowed access.
The response had HTTP status code 404.
```

**Comment by klokan** [comment]
CORS headers must be set on the Flask level @o1da

**Comment by o1da** [comment]
Header with 'Access-Control-Allow-Origin': '*' was already there.
Mirador doesn't says anything about CORS in my console, but there is an error if I fill url.

`openseadragon.js:16439 Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined`

**Comment by klokan** [comment]
In all cases - the manifest.json from e-codices runs fine and from Hawk not - so the problem is not on the mirador demo installation, but on our side.

**Comment by o1da** [comment]
Fixed - it works on the Mirador now.

**Comment by klokan** [comment]
Tested. Works fine. Thanks!

**Comment by klokan** [comment]
One more thing to fix @o1da: title should not be "Manifest of 000-test2" in Mirador - but the true title of the item!
