### ISSUE TITLE
S3FS flat folder data structure test

### ISSUE THREAD

**Issue by o1da** [klokantech/hawk#16]
Do a test to explore how our system would works if there are ten thousands and even more files in the local file cache.
Prove that a flat folder data structure is fine for our case and if not prepare concept of the folder hierarchy.
To be tested on the 100.000 sample dataset from #20

**Comment by klokan** [comment]
We will very probably use during the ingest (done in #13) a hash algorithm to create a hierarchy of directories to store the files.

For example this one (with sum of bytes of the name and directories with the hex values):
http://michaelandrews.typepad.com/the_technical_times/2009/10/creating-a-hashed-directory-structure.html

Required will be a patch of the IIPImage to support exactly the same algorithm.

It means to create two implementation of the hashing:
- python (for the ingestion on the server)
- C/C++ (for iipimage)

Another option would be to use md5/sha1 hash of the filename string (or a directory).
http://www.esebas.com/blog/2013/07/11/hashed-directory-file-storage/

Also, here are the limits and additional read:
http://stackoverflow.com/questions/466521/how-many-files-can-i-put-in-a-directory
http://superuser.com/questions/444286/linux-accessing-thousands-of-files-in-hash-of-directories

Decision to be made after initial tests.

**Comment by klokan** [comment]
CHANGE: It would make more sense to introduce the hierarchy of directories only on the side of internal S3FS local cache on the disk and make it hidden for the other processes via FUSE.

It means to test and patch only the S3FS code and have only one implementation on one place - instead of patching two projects - the hawk ingest code in python and the iipimage code.
This is better then approach described above.

**Comment by klokan** [comment]
@MartinMikita next week you should start on S3FS patch for this!
On Tuesday morning we can discuss details after the scrum hangout...

**Comment by o1da** [comment]
After the internal discussion we decided not to do any patch for this, because extensive s3fs file cache cleaning is going to be done instead #12
