### ISSUE TITLE
Ingestion task queue with Celery [C.1]

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#17]
To ensure proper distributed execution of downloading and conversion tasks on the available infrastructure (possibly multiple virtual machines) a task queue management system is required. We have good experience with Celery, which can run against local RabbitMQ broker or even utilise Amazon SQS. The ingested files must be re-encoded for a fast processing by image server.

This must be integrated with main Flask application #14 and it will call the independent ingest tasks #13.

It must hold status information about the tasks, repeat the failed tasks with defined scheme, and report on the status if asked from the ingestion API.

**Comment by klokan** [comment]
Moving to BETA - as it is easier to be done together with the initial implementation.

**Comment by o1da** [comment]
Celery is used now, there will be potentially some changes in the ingest itself, but work on this particular ticket is finished.
