### ISSUE TITLE
Sample dataset for Europeana Creative IIIF

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#20]
For further testing we need a sample dataset with about 100.000 images of various sizes and ideally various types (maps, photos, text pages, manuscripts, newspaper pages, etc).

Kennisland team @Taskamp and @mzeinstra should be able to provide us with such a dataset.

Either all files packed in a huge .zip archive (on which we receive a download link) or individual files uploaded to Amazon S3 (please create then a new bucket for these files).

These are going to be used for performance tests and also in the public demos of the service.

UPDATE:
Existing dataset outside of the cultural-heritage, which we can use for the tests:
MIRFLICKR: http://press.liacs.nl/mirflickr/#sec_download
FLICKR CC: http://webscope.sandbox.yahoo.com/catalog.php?datatype=i

**Comment by mzeinstra** [comment]
I've created a new bucket on s3 with the same account 'example.data.hawk.bucket' with a small dataset (11) of large images.

Before I start uploading large quantities of images from different heritage institutions, is this what you are looking for?

**Comment by klokan** [comment]
Thanks Maarten!

The tiny sample set is fine. We may need much larger amount of such files from Europeana or cultural heritage institutions (ideally over 100.000 files) and maybe some of these also with a larger size then the provided samples, if possible - to properly test the image serving infrastructure and the ingestion process at later point.

Please upload these individually to S3 - with public read rights ideally - so that we can ingest these images in the tests later on.

BTW The sample images has been added to the test set: http://klokantech.github.io/hawk/
Preview is possible also with the OpenSeaDragon-based viewer:
http://klokantech.github.io/hawk/viewers/openseadragon_hash.html#http://iiifhawk.klokantech.com/P00061121b/info.json

**Comment by klokan** [comment]
Is there an easy way how to download such sample set of images from Europeana directly?
Or is it possible to get the list of the very large amounts of download links of images from the Europeana API or from the dumps? Are you using any of these or where does your samples come from?

**Comment by mzeinstra** [comment]
Thanks for the reply.

I wrote two scripts, one to harvest metadata and direct links from all extra large, large and medium sized images from Europeana. Second, a script that downloads them from these providers and uploads them to the bucket. The Europeana Content Reuse Framework, will be introduced before the end of the month, that framework allows me to make these queries on the entire Europeana Database. At the moment I am working from a beta API, and dataset.

It might be faster to run that script from an EC2 instance instead of machine from our office. I however do not have the technical know-how how to do that.

**Comment by mzeinstra** [comment]
My machine has been uploading about 4 hours today. I believe we have somewhat in the neighbourhood of 1.100 images. As I am working with a limited set of images that are available from Europeana I have to makes sure that I don't continuously request images from a server and take it down. So I limited the uploads a bit.

**Comment by klokan** [comment]
Maybe you can provide us just with a list of the URLs to the images only - instead of uploading all the files?

It would be helpful to have access to the scripts you have made for calling the Europeana Content Reuse Framework - possibly in a gist.github.com? Is the API also documented somewhere (for a curiosity).

**Comment by mzeinstra** [comment]
Here is what I wrote: https://github.com/mzeinstra/Europeana-to-Amazon-s3

Here is the list I am using: https://github.com/mzeinstra/Europeana-to-Amazon-s3/blob/master/20150421LargeImages-openlylicensed.csv

Based on the beta dataset from Europeana and a script that I wrote to subtract high quality images:
https://github.com/mzeinstra/Europeana-to-Amazon-s3/blob/master/API-CRF-images.php

I use this script to upload to s3
https://github.com/mzeinstra/Europeana-to-Amazon-s3/blob/master/upload.php

and keep track of what has been done in a log file:
https://github.com/mzeinstra/Europeana-to-Amazon-s3/blob/master/done

Now, I am not a professional developer. If I code more than 8 hours per months than that would be a lot. So excuse my programming skills :)

**Comment by mzeinstra** [comment]
Is this something you can use for this ticket, do you want me to continue uploading to that bucket?

**Comment by klokan** [comment]
We can use what you have provided already - thanks.
The next step is the early version of the core app #14 with basic ingestion #13, then we will continue with tests of the ingestion and performance on S3FS and let you know...

**Comment by klokan** [comment]
Another nice dataset with large number (250k) of large files may be the USGS maps:
List at:
http://thor-f5.er.usgs.gov/ngtoc/metadata/misc/topomaps_all.zip
Links to individual huge JPEGs like:
http://ngmdb.usgs.gov/img4/ht_icons/Browse/NV/NV_Ely_321669_1963_250000.jpg

**Comment by klokan** [comment]
Sample data are prepared in this ticket.
The large ingest tests to be run under #35

**Comment by klokan** [comment]
The provided harvesting script requires Europeana API Key available from: http://www.europeana.eu/portal/myeuropeana#api-keys

@o1da the downloading script needs to be changed to generate HAWK Ingest API compatible JSON containing also the metadata - for the Ingest test #35.

We will save the generated JSON to a release of HAWK for the test purposes.

The code of the command-line utility [API-CRF-images.php](https://github.com/klokantech/Europeana-to-Amazon-s3/blob/master/API-CRF-images.php) to be improved in the fork: https://github.com/klokantech/Europeana-to-Amazon-s3

**Comment by mzeinstra** [comment]
Europeana's API has changed since I wrote that script. I'll see if I can improve what I've written there in the next couple of hours. I think I can simplify it + generate JSON output.

@o1da you can also find me on skype (mzeinstra) to discuss that script

**Comment by mzeinstra** [comment]
@o1da I've updated the script to be more concise, print JSON, have fewer calls to Europeana and point to the correct API endpoint: https://github.com/mzeinstra/Europeana-to-Amazon-s3/blob/master/API-CRF-images.php

It has no error correction and will allow empty fields. Which I think is great for testing the ingestion API ;)

**Comment by klokan** [comment]
Thanks @mzeinstra - the script has been now used for the test ingest.

**Comment by o1da** [comment]
Thank you @mzeinstra yours script really makes our work easier. I updated it a bit, it can be download from our fork https://github.com/klokantech/Europeana-to-Amazon-s3
