### ISSUE TITLE
embedhawk.klokantech.com - DNS

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#21]
Configure the DNS and set nginx to serve the prototype of embed service. It will run on a new EC2 machine.

The domain is a prototype for the planned: "embed.europeana.eu".

Configure GitHub auto-deploy for the master repository of hawk project on this.

Maybe use with a docker compose and make deploy via docker hub?

**Comment by klokan** [comment]
Docker with configured autobuild for the "embed" is at: https://registry.hub.docker.com/u/klokantech/embedhawk/

**Comment by o1da** [comment]
embed.europeana.eu server is prepared and working at http://embedhawk.klokantech.com/, but for now if I do some changes in the flask application I have to pull sources from github and restart docker containers manually.
Exact production setting with image from the docker hub will be discussed.

**Comment by o1da** [comment]
Will be discussed how to do a final deploy.

**Comment by klokan** [comment]
The embed.klokantech.com is running correctly.
Autodeploy or production deploy of new releases moved to FINAL milestone under #33.
