### ISSUE TITLE
Performance test

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#22]
Create graphs for a performance of test (with various number of visitors).

The test should compare:
- Standard setup vs
- Nginx memcached cache

And Kakadu JPEG2000 library performance
- With standard latest version
- With SpeedPack version of the library

The links to related tools and docs:
http://blog.modsaid.com/2014/04/stress-testing-with-siege-and-bombard.html
https://github.com/allardhoeve/bombard

keep in mind:
http://stackoverflow.com/questions/13823964/how-accurate-is-testing-with-siege-and-ab

**Comment by klokan** [comment]
We can also use a tool different then bombard for these tests - if there is a better one.

**Comment by klokan** [comment]
Distributed stress test will follow in #23

**Comment by klokan** [comment]
Moving to FINAL milestone - not essential for the contract.

**Comment by o1da** [comment]
We have standard configuration only now without SpeedPack version of JPEG2000 library. A new test should be run after the external memcache and new IIIF server binary will be adapted.

So this test ran on IIIF server itself with 170k usgs testing data. Thumbnails of 300px width were requested.

`siege -c50 -i -d 3 -t15m -q -f usgs_test.txt`

Where:
- `-c50` is maximal concurrency of 50 "users"
- `-i` is internet mode, so urls are tried randomly
- `-d 3` is a delay between a new concurrent user is add to test and it is time between 0-3 s
- `-t15m` test time is 15m
- `-q` is quiet mode, only overall results are printed
  *`-f usgs_test.txt` is a file with one url on line

```
Transactions:              22497 hits
/Availability:            100.00 %
Elapsed time:             899.20 secs
Data transferred:         419.50 MB
Response time:              0.49 secs
Transaction rate:          25.02 trans/sec
Throughput:             0.47 MB/sec
Concurrency:               12.37
Successful transactions:       22497
Failed transactions:               0
Longest transaction:            3.81
Shortest transaction:           0.00
```

22497 urls were tested without any failure, average latency were 0.47s per all concurrent requests.

Distributed test with almost same configuration follows
