### ISSUE TITLE
Unit tests on the Flask app

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#25]
While working on the endpoints we should ensure the app is covered with tests - ideally from the day 1.

See:
http://flask.pocoo.org/docs/0.10/testing/
https://github.com/jarus/flask-testing/
http://pythonhosted.org/Flask-Testing/

Ideally we can configure Travis on the repository and also coveralls.io - if this can be done fast.
First (in this ticket just the test) automation of the tests and test coverage stats later.

**Comment by o1da** [comment]
Some tests are added, it should be continually updated. I have just added "database wrapper", so I can use fake redis server during the testing without any changes in the code.

Tests: https://github.com/klokantech/hawk/blob/master/embed/test.py

Travis in #41
