### ISSUE TITLE
Sanitising HTML/JS in metadata

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#26]
During the import of the metadata we may need to validate the content for malformed content.

Read:
https://groups.google.com/forum/#!topic/iiif-discuss/1NJlfELHOs0

There are also examples of malformed content in the conversation.

**Comment by klokan** [comment]
Ingest task should be clever enough.

**Comment by o1da** [comment]
Done with 
http://bleach.readthedocs.org/en/latest/index.html

Html is allowed only for description field and there is a list for allowed tags. For now it is
`ALLOWED_TAGS = ['b', 'blockquote', 'code', 'em', 'i', 'li', 'ol', 'strong', 'ul']`

Everywhere else tags are striped.
