### ISSUE TITLE
Sequence possibilities/implications

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#27]
Does Hawk allow ingestion of sequences images as described in http://iiif.io/api/presentation/2.0/#sequence ?

Europeana supports multiple images of the same object, do we support that and what are the implication of it for the ingestion API?

_Example_
This object http://europeana.eu/portal/record/11613/ENTOMOLOGY_NM_CZECHREPUBLIC_E118w.html
has these high-res images:
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118a.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118b.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118c.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118d.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118e.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118f.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118g.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118h.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118i.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118j.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118k.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118l.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118m.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118n.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118o.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118p.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118q.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118r.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118s.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118t.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118u.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118v.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118w.jpg
http://pm.nm.cz/OpenUpData/Entomologie/Fotky/E118x.jpg

---

This is the summary of extra work to be done on top of what was planned:
- [x] Ingest JSON (https://github.com/klokantech/hawk/wiki/C.Ingest) to be extended for support of list of strings in the place of URL:
  `url: ["http://address1","http://adress2"]` possible instead of `url: "http://address"`.
- [x] Multiple ingest tasks created for one item - because one ingest task needs to download and recode **only one image** - it would be horrible to have a single tasks responsible for ingesting hundreds of pages of book at once.
- [x] Appropriate modification of the internal metadata storage to hold the information about the sequence
- [x] IIIF Manifest to expose the sequence (this is relatively natural)
- [x] iFrame embedding - the viewer should contain links to "Next" and "Previous" images - or even list of thumbnails - new JavaScript programming - a la https://openseadragon.github.io/examples/tilesource-sequence/ or http://www.bacarchive.org.uk/items/show/4794#zoom.
- [x] OEmbed does not have concept of sequences. It will probably need to expose _/identifier_ as the first page only - equal to request for _/identifier/0_. OEmbed for second page will be via _/identifier/1_, third for _/identifier/2_, etc. On these URLs will be also the zoomable viewer for one image only. 
- [x] Ingest task pushes the .jp2 files to the right place (identifier.jp2, identifier/1.jp2, identifier/2.jp2, etc.) in Amazon S3 and IIPImage can access these on URLs without .jp2.

**Comment by klokan** [comment]
It was not planned in the original specification.
We may look it up.

**Comment by mzeinstra** [comment]
Are we thinking about extra work here or just a different implementation of the already planned work?

**Comment by klokan** [comment]
This is the summary of extra work to be done on top of what was planned:
...
Individually these tasks looks quite OK, but all together it is already non-trivial number of time extra...

Update:
Sent to the top of this issue to show the progress of ticket in GitHub.

**Comment by o1da** [comment]
Done
