### ISSUE TITLE
iFrame embed design improvements

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#28]
Improvements of the design of the embedding part of the web - including all of the metadata for example.

Let's improve also the look&feel of the metadata overlays and implement correct responsibility of the CSS (after looking for best examples).

We may also upgrade OpenSeaDragon component to 2.0.0 (https://github.com/openseadragon/openseadragon/releases/tag/v2.0.0) - to have the latest fixes included (such as Retina support) - and probably host the OpenSeaDragon locally inside of the hern codebase as a static file (not served by Flask but by nginx directly in the production environment).

This is pre-production improvement of initial version done in #7

**Comment by klokan** [comment]
On meeting June 5th @mzeinstra and @taskamp mentioned they want to provide ideas and mockups or CSS for the fullscreen viewer used for iFrame embedding - such as http://embedhawk.klokantech.com/000-test2
with template at
https://github.com/klokantech/hawk/blob/master/embed/app/templates/iframe_openseadragon_inline.html

Keep in mind the "Next" / "Previous" links should be available for the sequences of images.
We were thinking of hiding the controls and transparent metadata overlay in case user is not hovering the viewer. In this moment there is no design applied from us...

This task is waiting for Kennisland team now (possibly @tomkr?)

**Comment by mzeinstra** [comment]
Uploading an image to Github seems to fail today so I've made our initial designs available on Dropbox: https://www.dropbox.com/sh/4zzjilzvapnequm/AABLa7u297xaO3xRt339eQ-4a?dl=0

For Klokan hawk_webdesign_photo.jpg is most relevant, everything except for the menu/search bar can be considered as a design for an iFrame.

Does this work for an initial idea?

**Comment by mzeinstra** [comment]
Does the oEmbed include this iFrame code or will we have a separate desgin for that?

**Comment by klokan** [comment]
There is no separate design for oEmbed.
oEmbed runs via the links to the JSON and XML documents included in this viewer.

**Comment by o1da** [comment]
Design is being improved by @tomkr via pull requests, so this ticket is no longer need.
