### ISSUE TITLE
Simplified URLs

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#29]
The original specification https://github.com/klokantech/hawk/wiki/B.Embed proposed a set of URLs for the embedding, which can be simplified while practically providing the same functionality. Simple is better... This ticket suggests simplification of the URLs exposed by the HAWK service.

The project can have only a single main URL per image:
http://embed.europeana.eu/[UNIQUE-ID]
- On this URL is the zoomable viewer showing the metadata responsively - exactly as it was originally planned.
- This page can also include the meta headers - to be used as the main URL for oEmbed embedding (so we can get rid of the otherwise quite useless `/oembed/[UNIQUE-ID]` urls showing the full resolution image.
  In this moment we have `/oembedprovider` which will become just `/oembed` (it is a single service - not per document) - this will reflect the best practice from YouTube and other services.
- IIIF protocol Presentation API manifest can be served from at http://embed.europeana.eu/[UNIQUE-ID]/manifest.json without a need for extra `/iiif/` prefix.
  I am keen to explore the validation of the JSON-LD data embedded in the HTML document of the image page instead of the extra manifest URL - which would make this even more beautiful.
  See: https://developers.google.com/schemas/formats/json-ld

If this is confirmed by @mzeinstra we can apply this change. To be discussed on the next meeting.

**Comment by ghost** [comment]
At the moment I don't foresee any problems with this simplification. I agree that the simpler the better.

**Comment by mzeinstra** [comment]
I Agree with @Taskamp this seems like an elegant enhancement.

**Comment by klokan** [comment]
Scheduled for BETA @o1da

**Comment by o1da** [comment]
It is done and deployed on http://embedhawk.klokantech.com/
