### ISSUE TITLE
Verify mappings in all services

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#30]
This ticket is here to verify their availability in all of the core metadata imports / exports.
These need to be checked:
- [x] Ingestion API
- [x] Viewer (META HEADERS + visible responsive DIV overlay)
- [x] oEmbed
- [x] IIIF Presentation API

Here is the relevant table:

| Label | Ingestion API | Viewer | oEmbed | Presentation API (IIIF) |
| --- | --- | --- | --- | --- |
| ID | ID |  |  | @id |
| Title | Title | dc:title | title | Label |
| Creator | Creator | dc:creator | author_name |  |
| Source | Source | dc:source | author_url |  |
| Institution | Institution | dc:publisher | provider_name |  |
| Institution Link | InstitutionLink |  | provider_url |  |
| License | License | dc:rights |  | license |
| Description | Description | dc:description |  | description |
| Image URL | ImageURL |  |  |  |

@mzinstra defined these mappings of metadata keys in the document: https://docs.google.com/document/d/1fNnDGo5cFOPgfDV61BQTvCbW6iJbFit0GQfwphgf7B4/edit#

**Comment by mzeinstra** [comment]
The table above provides the technical way that I see to represent this. I defer to your choices if from your experience in implementing these services you would do it differently.

**Comment by o1da** [comment]
Done, a few services are updated.
