### ISSUE TITLE
Service is going to live at embedr.eu

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#32]
embed.europeana.eu was a placeholder name. We have now chosen a definitive domain name: embedr.eu

I am in control over it's DNS records. Contact me when you need to make changes to that.

Also @taskamp and I are now also available at hello@embedr.eu

[update by @klokan] Tasks to do here:
- [x] @mzeinstra configures the domain to be administered from Amazon DNS (Route 53)
- [x] @klokantech: iiif.europeana.eu (iiifhawk.klokantech.com) -> http://iiif.embedr.eu
- [x] @klokantech: embed.europeana.eu (embedhawk.klokantech.com) -> http://media.embedr.eu

**Comment by klokan** [comment]
OK. To be done as part of FINAL milestone.

**Comment by klokan** [comment]
So is there going to be the mapping like:
iiif.europeana.eu -> http://iiif.embedr.eu
embed.europeana.eu/[UNIQUE-ID] -> www.embedr.eu/[UNIQUE-ID]
embed.europeana.eu/oembed -> www.embedr.eu/oembed

How do you plan to mix the URLs with the website prepared by the third-party?

**Comment by mzeinstra** [comment]
As discussed we will be presenting the service formally on July 10th as part of the end of the parent project Europeana Creative. The FINAL milestone officially closes at July 15th, we have to discuss if this will limit our presenting options.

I would be fine with still using a subdomain to solve the issue of mixing URLs

I can imagine that we use:
iiif.embedr.eu for the IIIF api

embedr.eu/m/{unique_ID}
embedr.eu/oembed
and let the third party developer solve this using a subdomein media.embedr.eu to refer to AWS

Would that work for you?

**Comment by klokan** [comment]
I guess ideal would be to have:
embedr.eu/ - project website
embedr.eu/{unique_ID} - for the main viewer as well as iframe embedding, omebed tags - the single page for one image
embedr.eu/{a-few-named-pages} - for whatever you want such as:
embedr.eu/blog/*
embedr.eu/pricing/
...

But here starts the complications if two parties are doing one web with different technologies...

You can't mix /{unique_ID} urls with a website on one domain if these are hosted on two different services (Amazon EC2 vs Heroku). The only way how to mix these (which makes sense for the beautiful URLs if the website will have anyway just a few static pages or a blog) without a proxy is to have both services on the same hosting and define rewrites in a webserver in the docker... which would mean again extra work for us now and possible responsibility for hosting of whatever third-party creates in future :-(.
- What is the `/m/` for?
- How can you the /oembed (implemented in our python code) make available on the web implemented by a third party?

You are probably forced to put our urls with /{unique_ID} and /oembed on a different domain then main the website.
Do you want to run embed.europeana.eu (now embedhawk.klokantech.com) on media.embedr.eu?

**Comment by mzeinstra** [comment]
I want to run media.embedr.eu instead of embed.europeana.eu

I'll include @tomkr in this ticket, he is our front-end developer. He might also have some ideas on how to solve this.

**Comment by klokan** [comment]
Summary of what should be done added in the ticker above.
KlokanTech will change the domains:
- iiif.europeana.eu (iiifhawk.klokantech.com) -> http://iiif.embedr.eu
- embed.europeana.eu (embedhawk.klokantech.com) -> http://media.embedr.eu

@mzeinstra - will move the DNS servers for embedr.eu to Amazon http://aws.amazon.com/route53/. This is required for the load-balancer to run correctly, and it mean we can make changes with amazon credentials

@tomkr - I would be very glad to meet you on Skype and break the ice ;-). Please write me an email at petr.pridal@klokantech.com.

**Comment by mzeinstra** [comment]
Embedr.eu is now available on Route 53

**Comment by o1da** [comment]
Done. Please start to use new names immediately.
