### ISSUE TITLE
Standardised deploy of new releases

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#33]
The process of deploy of changes done in GitHub code for the Flask app and ingest task code to the production servers must be standardised and documented.

We could use KlokanTech's docker-deploy process on the Amazon EC2 or go for rebuilding of the AMIs directly on the Amazon infrastructure, because AMIs are required for the load-balancer to work correctly.

**Comment by o1da** [comment]
For now the process of deploying changes to Amazon EC2 is manual and probably wouldn't change. iiif.embedr.eu runs behind Load Balancer and Auto Scaling and if any change occurs it have to be adopt on EC2 instance (better to do it and test it not on the production one). Next a new AMI have to be build from it and Load Balancer and Auto Scaling have to reconfigured to use a new AMI. And currently running EC2 instances have to be replaced be new ones.

As I mentioned in #55 the media.embedr.eu should be configured with Auto Scaling too, so the work with AMI is going to be the same.

If I have to be honest it potentially can be automated by AWS CLI (http://docs.aws.amazon.com/cli/latest/reference/ec2/create-image.html) and all needed reconfiguration too. But it isn't definitely trivial process (e.g. EC2 instance which serves as source for a new AMI have to be restarted during this process) and do it manually would be safer and easier (if AWS CLI is going to be used, much scripting work have to be done).

As I'm updating documentation now (and I'm going to do it continuously), this process is covered by readme.
