### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by o1da** [klokantech/hawk#34]
Documentation of the project:
- [x] Update wiki with the model definition from https://docs.google.com/document/d/1fNnDGo5cFOPgfDV61BQTvCbW6iJbFit0GQfwphgf7B4/edit#heading=h.kjguvyt0pvv2
- [x] Update wiki with changes introduced in sequence implementation: https://github.com/klokantech/hawk/issues/27
- [x] Add more documentation for deployment (with docker compose and individual containers) - in README.md in the individual folders
- [x] Improve documentation of source codes

**Comment by o1da** [comment]
Done

**Comment by klokan** [comment]
Updated main diagram:
![europeana-embedding-service-diagram](https://cloud.githubusercontent.com/assets/59284/8906048/75e248ba-346b-11e5-9cf6-ab60c82413d9.jpg)

AWS structure:
![aws-diagram-embedr](https://cloud.githubusercontent.com/assets/59284/8906521/a7313742-346f-11e5-801c-e06c07cf03db.jpg)

Possible future AWS structure:
![aws-diagram-embedr-future](https://cloud.githubusercontent.com/assets/59284/8906031/5acecce2-346b-11e5-95d1-4062a798230e.jpg)
