### ISSUE TITLE
Amazon EC2 + S3 deploy [A.2]

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#4]
Setup of a virtual machine with Amazon S3, installation with S3FS-FUSE, testing and initial performance optimization.

**Comment by klokan** [comment]
As the test data for ALPHA milestone we can use some (1000?) of the British Library Flickr images - stored as .jp2 already in the KlokanTech IIIF hosting.

**Comment by o1da** [comment]
EC2 machine is running, s3 storage is connected with s3fs and filed with testing data. Now we are running performance tests and optimising the configuration. It looks promising, s3fs has many parameters to play with.

**Comment by klokan** [comment]
The virtual machine is deployed now (details under #6).

The sample images are stored in Amazon S3 and transferred on demand to a local disk where the image server software provides IIIF (http://iiif.io) image service to the online visitors.

The detailed S3FS performance tests and configuration is described in the document:
https://docs.google.com/document/d/18YvJ9bf7NH1SrPxARyvcutzkhNVTz42y_KlxOnfYVuI/edit?usp=sharing

Complete installation protocol (with restricted access because it contains confidential information):
https://docs.google.com/a/klokantech.com/document/d/1OK0WziJ2Z-_lAiBJcWxRazL5se27OQ7WUcqnpVRE7fg/edit?usp=sharing
