### ISSUE TITLE
Item ID modification

### ISSUE THREAD

**Issue by o1da** [klokantech/hawk#40]
The max size of item ID was increased from 32 chars to 256 chars, because many of IDs from the Europeana data set #20 were longer. We should update wiki and use a hash (probably SHA512) during the communication (insert, delete) with Amazon CloudSearch, because it supports max 128 chars long keys.

**Comment by klokan** [comment]
To be put into WIKI.

**Comment by o1da** [comment]
Wiki is changed and hash is used instead of plain ID during the communication with CloudSearch
