### ISSUE TITLE
CloudSearch Item + Task

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#43]
It would be good to enrich the storage of the CloudSearch - to have an extra permanent storage of the core metadata next to our redis.

The `Item`:
- [x] timestamp of ingest
- [x] url / width / height

The `Batch` in a custom search domain:
- [x] store the already finished batches.

**Comment by mzeinstra** [comment]
It would be great if width and height become available through CloudSearch. That allows us to do some high quality maximum size embedding. 

See https://github.com/tomkr/embedr/issues/22 on my idea on this.

**Comment by o1da** [comment]
Image metadata are available on the CloudSearch now (for a new ingested item - I have to delete and ingest everything now).

**Comment by o1da** [comment]
Finished batches are on the CloudSearch (separate domain) too, but for now only as backup.

**Comment by o1da** [comment]
During the large ingest test #38 I noticed problem with store of completed batch on the CloudSearch. CloudSearch allowed document up to size of 5MB and json with thousands of item can be much larger. I'm not sure if the CloudSearch is good place to store completed batch.

**Comment by klokan** [comment]
After discussion the permanent storage for a batch is going to be implemented on the `Task` level - where each task will have batch_id - and request to a batch will select all tasks from CloudSearch.

Because of the CloudSearch limits a single Batch will have maximum 10.000 items and because of the upload limits the JSON must be less 100 MB (#39).

**Comment by o1da** [comment]
Batches and tasks are stored in local sqlite database. Batches aren't in redis at all, but tasks are in redis until they are finished and they are moved from redis to sqlite after finish and after request for batch status.
Cloud Search is used only for items now.

**Comment by o1da** [comment]
Limit for JSON 100MB size remains, but it can have more then 10 000 items, because Cloud Search isn't used for storing batches now.
