### ISSUE TITLE
Source not populated in Flask

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#51]
I noticed that source is not being populated on the viewer, this leads me to believe that it is not being populated in Flask.

Example: the item http://dev.embedr.eu/#/_08511_Detaliu_asp_k_17C6C52F_2C64_48E0_9A77_7D032BDEF14D
is ingestion like this: 

```
    {
        "id": "_08511_Detaliu_asp_k_17C6C52F_2C64_48E0_9A77_7D032BDEF14D",
        "institution": "CIMEC",
        "institution_link": "http:\/\/busy-api.de.a9sapp.eu\/40418049\/redirect?shownAt=http%3A%2F%2Fclasate.cimec.ro%2FDetaliu.asp%3Fk%3D17C6C52F-2C64-48E0-9A77-7D032BDEF14D%26bt%3Deuropeanaapi&provider=Athena&id=http%3A%2F%2Fwww.europeana.eu%2Fresolve%2Frecord%2F08511%2FDetaliu_asp_k_17C6C52F_2C64_48E0_9A77_7D032BDEF14D&profile=portal+rich",
        "url": [
            "http:\/\/www.cimec.ro\/p\/Clasate\/ETN_7300300_740-1.jpg"
        ],
        "license": "http:\/\/creativecommons.org\/publicdomain\/zero\/1.0\/",
        "source": "http:\/\/www.europeana.eu\/portal\/record\/\/08511\/Detaliu_asp_k_17C6C52F_2C64_48E0_9A77_7D032BDEF14D.html",
        "title": "P\u0103retar",
        "creator": "Rom\u00e2ni",
        "description": "Decor geometric"
    },
```

according to https://github.com/klokantech/hawk/blob/master/embed/app/templates/iframe_openseadragon_inline.html#L40 the institution should be a link to the source, but source seems to be empty. 

Is it being populated?

**Comment by o1da** [comment]
It was a bug - source wasn't been saved to the local database at the end. A new ingested items will be ok. If you want to correct previously ingested items a new ingest with old json file is needed - it only rewrites metadata without image processing, because it would recognize if images were processed previously.

**Comment by mzeinstra** [comment]
Thanks. 

For my info how does it recognise that the image is the same as the previous ingestion request?

**Comment by o1da** [comment]
Via url, if the url field is same for specific item in ingest.json (and on same position, only if sequence is used), nothing is needed to be done with image, only metadata are stored in the local database and they are pushed to the CloudSearch service. Without image processing it should be really fast.
