### ISSUE TITLE
Could we stop batch 33?

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#54]
In preparation of the demo I've wanted to re-ingest some high res images to solve that source link problem of #51 in our demo images, however batch 33 is still running, ingesting over 25.000 images. Batch 34 has our demo images.

@o1da is it possible to stop batch 33 so 34 can go ahead and ingest?

**Comment by o1da** [comment]
It is a problem, I can only purge all waiting tasks from celery. If you don't have item with sequence database should be fine and consistent. But you have to ingest everything what is pending again. Should I do it?
But I have to warn you, I haven't done it yet in this way.

**Comment by mzeinstra** [comment]
No lets leave it as is, I found other images to work with.

## 

Kennisland | www.kl.nl | t +31205756720 | m +31643053919 | @mzeinstra

**Comment by o1da** [comment]
Ok
