### ISSUE TITLE
Switch to production after final meeting

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#58]
On meeting on 27th we should discuss the switch to production - and do final tasks in the following days.

It is going to be probably:
- [x] Cleaning of the database (redis)
- [x] Cleaning of the S3 storage (clean bucket)
- [x] Cleaning of the CloudSearch domain

This means the whole system is going to be turned into production and new ingest of the data must happen.

We should also discuss the production costs of the system and possible _enhancements_ which are documented in the tickets.

**Comment by o1da** [comment]
Done
