### ISSUE TITLE
Keep docker registry up to date

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#60]
Is that the docker registry lacks behind the commits on Github. Can we update this, or is there a reason that these are out of sync?

https://registry.hub.docker.com/u/klokantech/embedhawk/

**Comment by klokan** [comment]
To test project on a local computer use `docker-compose` - as described at https://github.com/klokantech/hawk (bellow in README.md).

The docker hub registry is in fact not in use - building of the container happens on your machine directly.

Anyway - I have updated the config - so the Docker Hub public registry is now building our code again as well.

Still - keep in mind we use Docker Microservice approach - not Monolithic approach. The container is designed as microservice - it needs other microservices such as nginx and redis to run.

**Comment by klokan** [comment]
We could probably remove the machine from Docker Hub.

It would be nice to create a monolith container for use with Kitematic or plain Docker.
This would be only for people to start to play with the project directly on their computer - but it is not really practical for deployment on the Amazon infrastructure.

**Comment by mzeinstra** [comment]
I agree, it would be better to remove the docker from the registry to not confuse users about how you can use the repository.
