### ISSUE TITLE
Ingestion gives 404

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#61]
Hi,

I was testing the ingestion API, while I am able to request my latest successful ingest (user/pass obfuscated): 

```
url -H "Content-Type: application/json" --user user:pass -X GET http://media.embedr.eu/ingest?batch_id=1
```

but a ingestion call

```
curl -H "Content-Type: application/json" --user user:pass -X POST -d @info.json http://media.embedr.eu/ingest
```

gives a 404.

I did request a username/password change by mail today to reflect the production phase, so it might be that that causes this problem, however if the GET works I assume that the password was not changed.

**Comment by o1da** [comment]
Password haven't been changed lately, and it is the same for GET and POST. Can you provide me with json file? I think that problem is in invalid json. 404 is returned if json reading fails entirely too (before any item processing). I'm going to add some text info to 404 response in this case.

**Comment by mzeinstra** [comment]
Ah yes it was my JSON. I expect a 400 if my payload was not correct, a 404 for me looks like I post to the wrong page.

I now successfully posted my batch.

**Comment by o1da** [comment]
Response codes are changed and some text info is provided too.
