### ISSUE TITLE
IIIF call gives corrupted image

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#65]
Just to check. Is this also an effect of #63?

![rijksmuseum_sk-c-5](https://cloud.githubusercontent.com/assets/5627431/9244501/02a8e884-419c-11e5-9f06-0369c0bbfb6a.jpg)

http://iiifhawk.klokantech.com/Rijksmuseum_SK-C-5/full/204,/0/native.jpg

**Comment by o1da** [comment]
Yes, it is the same problem as described in #63 
Image which have been used only for one url is OK:
http://iiifhawk.klokantech.com/Rijksmuseum_wiki_SK-C-5/full/204,/0/native.jpg

**Comment by klokan** [comment]
@o1da - but this is a single tile. I am not that confident it has something to do with the cache in HAWK project.

This looks more like a bug in IIPImage itself.
- [x] @o1da Could you please provide a link to the related jp2 file?

If it can be reproduced on our computers we may file this as a bug of IIPImage.

**Comment by o1da** [comment]
jp2 image can be downloaded from
https://s3.eu-central-1.amazonaws.com/storage.hawk.bucket/Rijksmuseum_SK-C-5.jp2

With local IIIF server I didn't have any problem with this image and this problem disappeared on iiif.embedr.eu immediately after all caches were cleaned (browser too)  #63
