### ISSUE TITLE
How long does it take for material to be ingested into Cloud Search

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#69]
I've been ingesting material in to Embedr in the last few days and I can't find them in our search.

for example I should be able to find http://embedr.eu/europeana___2021657__216359/ using either 'museon' or 'familieportet' both give no responses.

I want to make sure that that process did not fail somewhere in the last few days. How does it usually take for ingested items to be present in Cloud Search?

**Comment by o1da** [comment]
The ingestion of one item is correctly done only if it is converted to JP2, added to local DB, uploaded to S3 and added to CloudSearch. If there is an whatever error in these steps, the whole item is purged from all systems. So you can't be able to see the item on embedr.eu and don't see it on CloudSearch, if so - it would be a bug.

The item with ID "europeana___2021657__216359" is correctly ingested. I can see it in the CloudSearch console. I can search it by combination of 'museon' and 'familieportet' there.

![snimek obrazovky porizeny 2015-09-22 13 38 31](https://cloud.githubusercontent.com/assets/2953202/10017809/d39a748a-6131-11e5-933b-feac9a25ba79.png)

This issue originates from CloudSearch search query with unappropriate parameters @tomkr probably should check how he builds this queries. 'museon' is in the 'institution' column and 'familieportet' is in the 'title' column.

This documentation should be checked:
http://docs.aws.amazon.com/cloudsearch/latest/developerguide/searching-compound-queries.html

**Comment by mzeinstra** [comment]
You are right, I was being misled by the system as it does reply to some but not all queries. Thanks for confirming this side is running as expected.
