### ISSUE TITLE
iFrame embed HTML/CSS template [B.2]

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#7]
Prepare and test a fullscreen IIIF viewer as a template for the Embed service.
By replacing the link to info.json or by embedding the info.json and basic metadata into the template itself (HTML title, h1, etc) we should get a perfect viewer for iframe embedding.

iframe embed code should be prepared as well.

Let's prepare two variants of the template:
- Based on OpenSeaDragon https://openseadragon.github.io/ code
- Based on KlokanTech's IIIFViewer code http://klokantech.github.io/iiifviewer/

The templates should be placed for the testing purposes into gh-pages branch for direct preview and verification. Lets use http://jekyllrb.com/docs/datafiles/

There will be two variants for each viewer:
- a static HTML file getting the info.json URL on client side by JavaScript (possibly from actual URL) - done already for IIIFViewer, see: http://klokantech.github.io/iiifviewer/#http://iiifhawk.klokantech.com/BM_Maps_100204668/info.json
- an HTML template - where sever will include the related values by a templating language (let's develop that now against Jekyll on gh-pages - but we will port it to Flask for the production use in Embed service).

**Comment by petrsloup** [comment]
Initial viewers deployed at:
http://klokantech.github.io/hawk/viewers/iiifviewer_inline.html
http://klokantech.github.io/hawk/viewers/iiifviewer_hash.html#http://iiifhawk.klokantech.com/BM_Maps_100204668/info.json
http://klokantech.github.io/hawk/viewers/openseadragon_inline.html
http://klokantech.github.io/hawk/viewers/openseadragon_hash.html#http://iiifhawk.klokantech.com/BM_Maps_100204668/info.json

To be further discussed (functionality, styling, IIIFViewer/OpenSeaDragon/KlokanTech attributions)

**Comment by klokan** [comment]
Thanks you @petrsloup - for now this is perfect.

**Comment by klokan** [comment]
@o1da please apply openseadragon_inline.html for now into the embedding app.

**Comment by o1da** [comment]
Done, it will be viewable after next deploy.

**Comment by klokan** [comment]
Metadata are not filled in the template yet - HTML title tag, H1, Copyright info must be in the template!

**Comment by o1da** [comment]
I have only title setted from metadata now. None other fields for metadata are prepared in the template. Should I put them below the title?

**Comment by klokan** [comment]
Thank you. This is fine for the initial implementation (beta).

The better metadata presentation and responsive design to be made under iFrame embed design improvements #28

**Comment by klokan** [comment]
An issue appeared @o1da - the `@id` of the map is wrong:
"http://iiifhawk.klokantech.com/cgi-bin/iiifserver.fcgi?iiif=000-test2.jp2" - should be the short variant!!!

**Comment by o1da** [comment]
It is ok, it was in my testing data only.
