### ISSUE TITLE
media.embedr.eu needs to be able to communicate over https

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#72]
We need a certificate for media.embedr.eu as websites that load over https don't allow http iFrame that load content of media.embedr.eu.

Preferably we have a wildcard SSL certificate for the entire domain embedr.eu

@klokan what are our options?

**Comment by klokan** [comment]
With the standard process you may need to purchase multiple certificates or a single wildcard SSL certificate which must be configured for all different services: iiif.embedr.eu, media.embedr.eu and embedr.eu dev.embedr.eu. Then all the servers would require reconfiguration.

Alternative would be to use a CDN which supports SSL (https) directly - and put it in front of our http servers. Amazon Cloudfront is an option. They give you automatically their domain name https://xxxx.cloudfront.net/...
To use it with your own domain more configuration is required: See https://aws.amazon.com/cloudfront/custom-ssl-domains/

There are CDNs which gives you https proxy automatically (either on their domain or even on your domains) - some even for free.

If we should set this up for you we need access to the DNS administration of the domain (provided via a private secure channel to me).

**Comment by mzeinstra** [comment]
I've purchased a wildcard certificate. How should I get this certificate to you?

**Comment by klokan** [comment]
Private sharing - such as private Google Drive?

Also - please be aware that we are running out of credit on maintenance for 2016 soon. Timesheets for work done until now are available...

**Comment by mzeinstra** [comment]
@klokan did you receive the document?

Also I am interested in those timesheets

**Comment by klokan** [comment]
SSL certificate received.

To be deployed on iiif.embedr.eu and media.embedr.eu domains latest tomorrow by 11:00.

**Comment by o1da** [comment]
@mzeinstra Do we have all need files, especially private.key?
`-_embedr_eu.crt` file alone isn't enough to configure SSL.

Look at https://gist.github.com/bradmontgomery/6487319

Do you have mentioned .zip file and key file?
I have to leave now I will finish it tomorrow at approx 10:00

**Comment by mzeinstra** [comment]
@o1da lets postpone this then. I will launch the service at 10:00 tomorrow during a conference.

**Comment by o1da** [comment]
Ok, I will wait for all files.

**Comment by klokan** [comment]
Related (for load balancer): http://aws.amazon.com/certificate-manager/
