### ISSUE TITLE
Removed items need better error code (enhancement)

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#78]
at the moment removed items show up as:

```
The item is being ingested
```

( http://embedr.eu/europeana___2032007__SE_KAPY_HLA_HA9950/ ).

We need to have a more accurate code or load an image that conveys a proper message.

Relates to 404s: https://github.com/tomkr/embedr/issues/75

**Comment by o1da** [comment]
It was a bug associated with last ingestion changes and it is solved now.

**Comment by mzeinstra** [comment]
This is strange, I removed the items (and not by mistake).

Did you revert that? :)

**Comment by o1da** [comment]
Yes, all items with `The item is being ingested` info were reverted. I had to solve wrong state of some items after bug repair and reingestion seemed to be the most safe approach. I didn't take into account that these items were going to be deleted.
Sorry, please delete them again :)
