### ISSUE TITLE
We can spin down the additional ingestion server for now (after batch 77)

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#79]
I don't expect to run any more ingestion batches this year after batch 77 is done (0 ok, 5798 pending 0 errors). 

We can spin down this machine after that is done.

**Comment by mzeinstra** [comment]
Batch 77 is done, we can remove the dedicated ingestion server for now.

**Comment by o1da** [comment]
Server is stopped - it can be restored at any time, but now it doesn't cost anything.
