### ISSUE TITLE
S3FS listing patch

### ISSUE THREAD

**Issue by o1da** [klokantech/hawk#9]
We have to make a patch for S3FS to speed up response for a file which is not on S3. Avoidance of the listing operation is crucial here. We don't need listing at all for our use case, so we can easily change behavior of the list_bucket function in https://github.com/s3fs-fuse/s3fs-fuse/blob/master/src/s3fs.cpp

It would be probably OK if this function would response with empty string without any connection to S3 itself.

**Comment by klokan** [comment]
@MartinMikita coding to be done in a 'listing' branch under https://github.com/klokantech/s3fs-fuse

**Comment by MartinMikita** [comment]
Function `list_bucket` returns empty list.
- `ls` shows empty list for existing directory, or error if directory does not exist (correct behaviour)
- `ls *.jp2` with wildcard not permitted
- `ls <file>` working as before change

https://github.com/klokantech/s3fs-fuse/tree/listing

**Comment by klokan** [comment]
Thanks @MartinMikita!

Could you please revert the two commits, create a single commit, and ensure there are no changes of end-of-line character in half of the file?
From the diff must be clearly visible the modifications you have done...

**Comment by klokan** [comment]
Done in: 
https://github.com/klokantech/s3fs-fuse/commit/7a583eb4ec72a75042fd03e2c2da7abd2718859f

**Comment by klokan** [comment]
@o1da part of the deploy should be compiling of the hawk branch of s3fs-fuse:
https://github.com/klokantech/s3fs-fuse/tree/hawk

Finished. In case of issues we reopen.
